# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b31f094d8699f5cd8128ba566fa89c066b97a57c9495bb49450ddbcdfb9a1c5827388395f5827576063999be1f4415ee4a2de551880c39701de016f4d9fba14

test:
  secret_key_base: dcbbdf29a4eeebd6664589a6b27b25956c1187e34942536502084d295a393f3c9f119ce3d1ecc62752a6f5f059da69c43e52c9cf369aea3342719bc0b2b21fea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
